### ISSUE TITLE
Have you encountered memory leaks?

### ISSUE THREAD

**Issue by Pinkolik** [hvalev/monero-node#79]
Hello!
I'm trying to run this on my Orange PI 3 LTS (2 GB ram). And it constantly kills my server by consuming all of its ram. It starts normally at first but then eats everything up. Only server restart can help with this.

I already tried:
block-sync-size=1 and block_tor.txt.

As a temporary workaround, I added mem_limit: 500m to my docker-compose, so it constantly restarts itself.

Do you have any other suggestions I could try?

Thank you in advance!

**Comment by hvalev** [comment]
Hi, a quick update. I have now also started experiencing some memory issues with the container, since I moved it to a more 'busy' system. A possible, albeit imperfect solution is to add the parameters below to your docker compose file. What they do is limit the available memory to the container as to not crash your other applications. When monerod eventually exceeds this limit, the docker daemon will simply restart it. Depending on how much maximum memory you allocate, the restarts can vary from frequent to infrequent. But at least you got your service running almost 24/7 barring the boot-up times.

```
restart: unless-stopped
deploy:
  resources:
    limits:
      memory: 2000M
```
